In [1]:
pwd

u'C:\\Users\\dilip'

In [2]:
my_list = [1,2,3,4]

In [3]:
import numpy as np

In [5]:
arry = np.array(my_list)

In [6]:
arry

array([1, 2, 3, 4])

In [7]:
my_mar = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_mar

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
T1 = np.array(my_mar)

In [11]:
T1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [15]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [16]:
np.ones(3)

array([ 1.,  1.,  1.])

In [19]:
np.ones((4,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [20]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [22]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [23]:
np.random.rand(5)

array([ 0.03066419,  0.45262774,  0.4882561 ,  0.9941715 ,  0.29567429])

In [24]:
np.random.rand(5,5)

array([[ 0.55710498,  0.37278778,  0.62380287,  0.60511823,  0.42172686],
       [ 0.79693224,  0.41313016,  0.88489584,  0.65445791,  0.78306356],
       [ 0.08816719,  0.08392567,  0.17116524,  0.15067015,  0.29005521],
       [ 0.41574043,  0.8754546 ,  0.65732155,  0.97708422,  0.55200258],
       [ 0.34460831,  0.58538787,  0.51692628,  0.62624082,  0.1751571 ]])

In [25]:
np.random.randn(2)

array([-2.35519189,  0.69982185])

In [26]:
np.random.randn(5,5)

array([[-2.08290765,  0.96452335,  0.33698275, -1.07783353,  0.20722713],
       [-0.39088202,  1.45646449,  0.13680313, -1.05460658,  1.02354488],
       [ 0.44305314,  1.47724044, -2.20316757,  0.2471381 , -1.42806743],
       [ 0.21513575,  0.45720489, -0.30467978,  0.04357947, -1.25659993],
       [ 0.98387107, -0.03274668, -1.26587669, -0.91941472, -0.81076511]])

In [39]:
np.random.randint(1,100,10)

array([38, 79, 11, 99, 64, 58, 97, 98, 33, 84])

In [40]:
arr = np.arange(25)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
arr_2=np.random.randint(0,100,10)

In [44]:
arr_2

array([ 8, 68, 22, 93, 33, 10, 96, 84, 18, 28])

In [45]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arr_2.max()

96

In [47]:
arr_2.min()

8

In [49]:
arr_2.argmax()

6

In [50]:
arr_2.argmin()

0

In [52]:
arr.shape

(25L,)

In [53]:
arr.dtype

dtype('int32')

In [54]:
from numpy.random import randint

In [56]:
randint(1,10)

7